services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - course-manager-network

volumes:
  node_modules:

networks:
  course-manager-network:
    external: true
