services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - course-manager-network

networks:
  course-manager-network:
    external: true
