services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - "start-dev"
    volumes:
      - ./config:/opt/keycloak/data
    networks:
      - course-manager-network

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WATCHPACK_POLLING: true # enable Next.js hot reloading
    env_file:
      - .env
      - .env.local
    depends_on:
      - keycloak
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - course-manager-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - course-manager-network

volumes:
  keycloak-data:
  mysql-data:
networks:
  course-manager-network:
    external: true
