services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST_IP: ${HOST_IP}
      WATCHPACK_POLLING: true
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - course-manager-network
      - keycloak-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - course-manager-network

volumes:
  mysql-data:
networks:
  course-manager-network:
    external: true
  keycloak-network:
    external: true
